remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: CTB2MD - Cherrytree to Obsidian Migration Tool [macOS]
description: A native macOS tool to convert your Cherrytree notes to Obsidian-compatible Markdown format
show_downloads: true
github:
  zip_url: https://github.com/Polyx10/CTB2MD/releases/latest/download/CTB2MD_v1.0.0.zip
  repository_url: https://github.com/Polyx10/CTB2MD
